Update Skydoc dependency.
After updating to bazel 0.21:

ERROR: error loading package '': Encountered error while reading extension
file 'sass/sass.bzl': no such package '@io_bazel_rules_sass//sass': The native
git_repository rule is deprecated.
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") for a
replacement.

... and then a couple more errors after fixing one.

This updates the Skydoc depdency versions to those recommended in the
starting docs: https://skydoc.bazel.build/docs/getting_started.html